# Generated by Django 5.2.1 on 2025-06-01 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0001_initial'),
    ]

    operations = [
    ]
