# Generated by Django 5.2.1 on 2025-06-01 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0002_rename_averagetries_problem_averagetries1_and_more'),
    ]

    operations = [
    ]
