# Generated by Django 5.2.1 on 2025-06-01 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0003_rename_averagetries1_problem_averagetries_and_more'),
    ]

    operations = [
    ]
