# Generated by Django 5.2.1 on 2025-06-02 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0005_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='problem_solved_user',
            name='solved_at',
            field=models.DateTimeField(default="2025-01-01 00:00:00"),
            preserve_default=False,
        ),
    ]
