# Generated by Django 5.2.1 on 2025-06-02 00:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('problems', '0006_problem_solved_user_solved_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='problem_solved_user',
            name='solved_at',
        ),
    ]
