# Generated by Django 5.2.1 on 2025-05-30 06:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='problem',
            fields=[
                ('_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=128)),
                ('tag', models.JSONField(blank=True)),
                ('acceptedUserCount', models.IntegerField(default=0)),
                ('isSolvable', models.BooleanField(default=True)),
                ('level', models.IntegerField()),
                ('averageTries', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='user',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, unique=True)),
                ('password', models.CharField(max_length=32)),
                ('baekjoon_id', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='problem_solved_user',
            fields=[
                ('_id', models.AutoField(primary_key=True, serialize=False)),
                ('problemId', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='routine.user')),
            ],
        ),
    ]
