# Generated by Django 5.2.1 on 2025-05-30 06:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('routine', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='problem',
        ),
        migrations.DeleteModel(
            name='problem_solved_user',
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
